# https://www.youtube.com/watch?v=P1dzHNgAtvg
# Lesson 4 5 LED Binary Counter

from machine import Pin
from time import sleep

led1 = Pin(15,Pin.OUT)
led2 = Pin(14,Pin.OUT)
led3 = Pin(13,Pin.OUT)
led4 = Pin(12,Pin.OUT)
led5 = Pin(11,Pin.OUT)
snooze = .5

while True:
    print("")
    print("Counting Up")
    print("")
    
    led1.value(0)
    led2.value(0)
    led3.value(0)
    led4.value(0)
    led5.value(0)
    print("This is Decimal Zero - All LEDs off.")
    sleep(snooze)
    
    led1.value(1)
    led2.value(0)
    led3.value(0)
    led4.value(0)
    led5.value(0)
    print("This is Decimal One.")
    sleep(snooze)
    
    led1.value(0)
    led2.value(1)
    led3.value(0)
    led4.value(0)
    led5.value(0)
    print("This is Decimal Two.")
    sleep(snooze)
    
    led1.value(1)
    led2.value(1)
    led3.value(0)
    led4.value(0)
    led5.value(0)
    print("This is Decimal Three.")
    sleep(snooze) 
    
    led1.value(0)
    led2.value(0)
    led3.value(1)
    led4.value(0)
    led5.value(0)
    print("This is Decimal Four.")    
    sleep(snooze)
    
    led1.value(1)
    led2.value(0)
    led3.value(1)
    led4.value(0)
    led5.value(0)
    print("This is Decimal Five.")
    sleep(snooze)
    
    led1.value(0)
    led2.value(1)
    led3.value(1)
    led4.value(0)
    led5.value(0)
    print("This is Decimal Six.")
    sleep(snooze)
    
    led1.value(1)
    led2.value(1)
    led3.value(1)
    led4.value(0)
    led5.value(0)
    print("This is Decimal Seven.")
    sleep(snooze)
    
    led1.value(0)
    led2.value(0)
    led3.value(0)
    led4.value(1)
    led5.value(0)
    print("This is Decimal Eight.")
    sleep(snooze)
    
    led1.value(1)
    led2.value(0)
    led3.value(0)
    led4.value(1)
    led5.value(0)
    print("This is Decimal Nine.")
    sleep(snooze)
    
    led1.value(0)
    led2.value(1)
    led3.value(0)
    led4.value(1)
    led5.value(0)
    print("This is Decimal Ten.")
    sleep(snooze)
    
    led1.value(1)
    led2.value(1)
    led3.value(0)
    led4.value(1)
    led5.value(0)
    print("This is Decimal Eleven.")
    sleep(snooze)
    
    led1.value(0)
    led2.value(0)
    led3.value(1)
    led4.value(1)
    led5.value(0)
    print("This is Decimal Twelve.")
    sleep(snooze)
    
    led1.value(1)
    led2.value(0)
    led3.value(1)
    led4.value(1)
    led5.value(0)
    print("This is Decimal Thirteen.")
    sleep(snooze)
    
    led1.value(0)
    led2.value(1)
    led3.value(1)
    led4.value(1)
    led5.value(0)
    print("This is Decimal Fourteen.")
    sleep(snooze)
    
    led1.value(1)
    led2.value(1)
    led3.value(1)
    led4.value(1)
    led5.value(0)
    print("This is Decimal Fifteen.")
    sleep(snooze)
    
    led1.value(0)
    led2.value(0)
    led3.value(0)
    led4.value(0)
    led5.value(1)
    print("This is Decimal Sixteen.")
    sleep(snooze)
    
    led1.value(1)
    led2.value(0)
    led3.value(0)
    led4.value(0)
    led5.value(1)
    print("This is Decimal Seventeen.")
    sleep(snooze)
    
    led1.value(0)
    led2.value(1)
    led3.value(0)
    led4.value(0)
    led5.value(1)
    print("This is Decimal Eighteen.")
    sleep(snooze)
    
    led1.value(1)
    led2.value(1)
    led3.value(0)
    led4.value(0)
    led5.value(1)
    print("This is Decimal Nineteen.")
    sleep(snooze)
    
    led1.value(0)
    led2.value(0)
    led3.value(1)
    led4.value(0)
    led5.value(1)
    print("This is Decimal Twenty.")
    sleep(snooze)
       
    led1.value(1)
    led2.value(0)
    led3.value(1)
    led4.value(0)
    led5.value(1)
    print("This is Decimal Twenty One.")
    sleep(snooze)
    
    led1.value(0)
    led2.value(1)
    led3.value(1)
    led4.value(0)
    led5.value(1)
    print("This is Decimal Twenty Two.")
    sleep(snooze)
    
    led1.value(1)
    led2.value(1)
    led3.value(1)
    led4.value(0)
    led5.value(1)
    print("This is Decimal Twenty Three.")
    sleep(snooze)
    
    led1.value(0)
    led2.value(0)
    led3.value(0)
    led4.value(1)
    led5.value(1)
    print("This is Decimal Twenty Four.")
    sleep(snooze)
    
    led1.value(1)
    led2.value(0)
    led3.value(0)
    led4.value(1)
    led5.value(1)
    print("This is Decimal Twenty Five.")
    sleep(snooze)
    
    led1.value(0)
    led2.value(1)
    led3.value(0)
    led4.value(1)
    led5.value(1)
    print("This is Decimal Twenty Six.")
    sleep(snooze)
    
    led1.value(1)
    led2.value(1)
    led3.value(0)
    led4.value(1)
    led5.value(1)
    print("This is Decimal Twenty Seven.")
    sleep(snooze)
    
    led1.value(0)
    led2.value(0)
    led3.value(1)
    led4.value(1)
    led5.value(1)
    print("This is Decimal Twenty Eight.")
    sleep(snooze)
    
    led1.value(1)
    led2.value(0)
    led3.value(1)
    led4.value(1)
    led5.value(1)
    print("This is Decimal Twenty Nine.")
    sleep(snooze)
    
    led1.value(0)
    led2.value(1)
    led3.value(1)
    led4.value(1)
    led5.value(1)
    print("This is Decimal Thirty.")
    sleep(snooze)
    
    led1.value(1)
    led2.value(1)
    led3.value(1)
    led4.value(1)
    led5.value(1)
    print("This is Decimal Thirty One.")
    sleep(snooze)
    
# Half time show here
    print("")
    print("Half-Time show goes here.")
    print("")
    sleep(10)
    
    print("")
    print("Counting Down")
    print("")
    
    led1.value(1)
    led2.value(1)
    led3.value(1)
    led4.value(1)
    led5.value(1)
    print("This is Decimal Thirty One.")
    sleep(snooze)
           
    led1.value(0)
    led2.value(1)
    led3.value(1)
    led4.value(1)
    led5.value(1)
    print("This is Decimal Thirty.")
    sleep(snooze)
        
    led1.value(1)
    led2.value(0)
    led3.value(1)
    led4.value(1)
    led5.value(1)
    print("This is Decimal Twenty Nine.")
    sleep(snooze)
    
    led1.value(0)
    led2.value(0)
    led3.value(1)
    led4.value(1)
    led5.value(1)
    print("This is Decimal Twenty Eight.")
    sleep(snooze)
        
    led1.value(1)
    led2.value(1)
    led3.value(0)
    led4.value(1)
    led5.value(1)
    print("This is Decimal Twenty Seven.")
    sleep(snooze)
      
    led1.value(0)
    led2.value(1)
    led3.value(0)
    led4.value(1)
    led5.value(1)
    print("This is Decimal Twenty Six.")
    sleep(snooze)
   
    led1.value(1)
    led2.value(0)
    led3.value(0)
    led4.value(1)
    led5.value(1)
    print("This is Decimal Twenty Five.")
    sleep(snooze)
    
    led1.value(0)
    led2.value(0)
    led3.value(0)
    led4.value(1)
    led5.value(1)
    print("This is Decimal Twenty Four.")
    sleep(snooze)
    
    led1.value(1)
    led2.value(1)
    led3.value(1)
    led4.value(0)
    led5.value(1)
    print("This is Decimal Twenty Three.")
    sleep(snooze)
    
    led1.value(0)
    led2.value(1)
    led3.value(1)
    led4.value(0)
    led5.value(1)
    print("This is Decimal Twenty Two.")
    sleep(snooze)
      
    led1.value(1)
    led2.value(0)
    led3.value(1)
    led4.value(0)
    led5.value(1)
    print("This is Decimal Twenty One.")
    sleep(snooze)
    
    led1.value(0)
    led2.value(0)
    led3.value(1)
    led4.value(0)
    led5.value(1)
    print("This is Decimal Twenty.")
    sleep(snooze)
    
    led1.value(1)
    led2.value(1)
    led3.value(0)
    led4.value(0)
    led5.value(1)
    print("This is Decimal Nineteen.")
    sleep(snooze)
    
    led1.value(0)
    led2.value(1)
    led3.value(0)
    led4.value(0)
    led5.value(1)
    print("This is Decimal Eighteen.")
    sleep(snooze)
   
    led1.value(1)
    led2.value(0)
    led3.value(0)
    led4.value(0)
    led5.value(1)
    print("This is Decimal Seventeen.")
    sleep(snooze)
    
    led1.value(0)
    led2.value(0)
    led3.value(0)
    led4.value(0)
    led5.value(1)
    print("This is Decimal Sixteen.")
    sleep(snooze)
    
    led1.value(1)
    led2.value(1)
    led3.value(1)
    led4.value(1)
    led5.value(0)
    print("This is Decimal Fifteen.")
    sleep(snooze)
    
    led1.value(0)
    led2.value(1)
    led3.value(1)
    led4.value(1)
    led5.value(0)
    print("This is Decimal Fourteen.")
    sleep(snooze)
   
    led1.value(1)
    led2.value(0)
    led3.value(1)
    led4.value(1)
    led5.value(0)
    print("This is Decimal Thirteen.")
    sleep(snooze)
        
    led1.value(0)
    led2.value(0)
    led3.value(1)
    led4.value(1)
    led5.value(0)
    print("This is Decimal Twelve.")
    sleep(snooze)
    
    led1.value(1)
    led2.value(1)
    led3.value(0)
    led4.value(1)
    led5.value(0)
    print("This is Decimal Eleven.")
    sleep(snooze)
    
    led1.value(0)
    led2.value(1)
    led3.value(0)
    led4.value(1)
    led5.value(0)
    print("This is Decimal Ten.")
    sleep(snooze)
    
    led1.value(1)
    led2.value(0)
    led3.value(0)
    led4.value(1)
    led5.value(0)
    print("This is Decimal Nine.")
    sleep(snooze)
    
    led1.value(0)
    led2.value(0)
    led3.value(0)
    led4.value(1)
    led5.value(0)
    print("This is Decimal Eight.")
    sleep(snooze)
 
    led1.value(1)
    led2.value(1)
    led3.value(1)
    led4.value(0)
    led5.value(0)
    print("This is Decimal Seven.")
    sleep(snooze)
 
    led1.value(0)
    led2.value(1)
    led3.value(1)
    led4.value(0)
    led5.value(0)
    print("This is Decimal Six.")
    sleep(snooze)
    
    led1.value(1)
    led2.value(0)
    led3.value(1)
    led4.value(0)
    led5.value(0)
    print("This is Decimal Five.")
    sleep(snooze)
    
    led1.value(0)
    led2.value(0)
    led3.value(1)
    led4.value(0)
    led5.value(0)
    print("This is Decimal Four.")    
    sleep(snooze)
    
    led1.value(1)
    led2.value(1)
    led3.value(0)
    led4.value(0)
    led5.value(0)
    print("This is Decimal Three.")
    sleep(snooze)
    
    led1.value(0)
    led2.value(1)
    led3.value(0)
    led4.value(0)
    led5.value(0)
    print("This is Decimal Two.")
    sleep(snooze)
    
    led1.value(1)
    led2.value(0)
    led3.value(0)
    led4.value(0)
    led5.value(0)
    print("This is Decimal One.")
    sleep(snooze)

    led1.value(0)
    led2.value(0)
    led3.value(0)
    led4.value(0)
    led5.value(0)
    print("This is Decimal Zero - All LEDs off.")
    sleep(snooze)
    
    sleep(1)
    # Start again